[project]
name = "tdsproject2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.0",
    "openai>=1.57.4",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
